language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r dev-requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install -r dev-requirements.txt; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r dev-requirements-py3.txt; fi

script: make test
